key: Suicide_Model
kind: model
iter: 0
tree: 962732650f2c4144bc5450e3ac432564
target_path: ./MLRun_data/Data/models/
hash: e70553803d5c99d65809d38895bb39839349454f
size: 16778151
db_key: train_model_Suicide_Model
model_file: Suicide_Model.pkl
framework: ''
producer:
  name: train_model
  kind: run
  uri: suicide-pred-ahmadkhan242/962732650f2c4144bc5450e3ac432564
  owner: ahmadkhan242
sources:
- name: input_ds
  path: ./MLRun_data/Data/data/suicide_dataset_transformed.csv
project: suicide-pred-ahmadkhan242
updated: '2021-07-04T18:22:59.730708+00:00'
