key: Suicide_Model
kind: model
iter: 0
tree: bbbfccd7a3bd49409297cfa7f637fa36
target_path: /media/ahmadkhan242/A/MLRUn/Suicidal-post-detection/Flask/MLRun_data/Data/models/
hash: 473e462e3c893a5d5b350fbbef0db5bc91c3c6e6
size: 16778151
db_key: train_model_Suicide_Model
model_file: Suicide_Model.pkl
framework: ''
producer:
  name: train_model
  kind: run
  uri: suicide-pred-ahmadkhan242/bbbfccd7a3bd49409297cfa7f637fa36
  owner: ahmadkhan242
sources:
- name: input_ds
  path: /media/ahmadkhan242/A/MLRUn/Suicidal-post-detection/Flask/MLRun_data/Data/data/suicide_dataset_transformed.csv
project: suicide-pred-ahmadkhan242
updated: '2021-07-05T17:29:15.999573+00:00'
