key: Suicide_Model
kind: model
iter: 0
tree: 805d6fd3e5ad42c69004912c421d9c56
target_path: ./MLRun_data/Data/models/
hash: e70553803d5c99d65809d38895bb39839349454f
size: 16778151
db_key: train_model_Suicide_Model
model_file: Suicide_Model.pkl
framework: ''
producer:
  name: train_model
  kind: run
  uri: suicide-pred-ahmadkhan242/805d6fd3e5ad42c69004912c421d9c56
  owner: ahmadkhan242
sources:
- name: input_ds
  path: ./MLRun_data/Data/data/suicide_dataset_transformed.csv
project: suicide-pred-ahmadkhan242
updated: '2021-07-04T18:11:54.125736+00:00'
